CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30)
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "lastname" varchar(90) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "roleId" int NOT NULL,
  "isActive" boolean,
  "createdAt" date NOT NULL,
  "updatedAt" date
);

CREATE TABLE "restaurants" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" varchar(255),
  "address" varchar(100) NOT NULL,
  "photo" varchar(140),
  "owner" int NOT NULL
);

CREATE TABLE "tables" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurantId" int NOT NULL,
  "capacity" int NOT NULL,
  "isAvailable" boolean NOT NULL DEFAULT true
);

CREATE TABLE "reservations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "clientId" int NOT NULL,
  "restaurantCode" int NOT NULL,
  "tableId" int,
  "numDiners" int NOT NULL,
  "reservationDate" timestamp NOT NULL,
  "status" varchar(30)
);

ALTER TABLE "restaurants" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("roleId") REFERENCES "roles" ("id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("clientId") REFERENCES "users" ("id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("restaurantCode") REFERENCES "restaurants" ("id");

ALTER TABLE "tables" ADD FOREIGN KEY ("restaurantId") REFERENCES "restaurants" ("id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("tableId") REFERENCES "tables" ("id");

insert into roles(id,name) values(1,'ADMIN'), (2,'CUSTOMER');